/*
	function: addSection
	purpose : The board is removed after each password, hence, this function
			  "refreshes" or "resets" the confirmation board after each password. 
			  All pieces the user once entered are removed.  
*/
function addSection(){
	var newSec = "<div id='sec'><table id='confirmboard'><tr><td><div class='ctile' id='cr1c1' style='background-color:black'></div></td><td><div class='ctile' id='cr1c2'></div></td><td><div class='ctile' id='cr1c3' style='background-color:black'></div></td><td><div class='ctile' id='cr1c4'></div></td></tr><tr><td><div class='ctile' id='cr2c1'></div></td><td><div class='ctile' id='cr2c2' style='background-color:black'></div></td><td><div class='ctile' id='cr2c3'></div></td><td><div class='ctile' id='cr2c4' style='background-color:black'></div></td></tr><tr><td><div class='ctile' id='cr3c1' style='background-color:black'></div></td><td><div class='ctile' id='cr3c2'></div></td><td><div class='ctile' id='cr3c3' style='background-color:black'></div></td><td><div class='ctile' id='cr3c4'></div></td></tr><tr><td><div class='ctile' id='cr4c1'></div></td><td><div class='ctile' id='cr4c2' style='background-color:black'></div></td><td><div class='ctile' id='cr4c3'></div></td><td><div class='ctile' id='cr4c4' style='background-color:black'></div></td></tr></table><div id='piecesBox'><img class='boximgs drag' id='bq' src='Pieces/blackQueen.png' title='Black Queen'/><img class='boximgs drag' id='wq' src='Pieces/whiteQueen.png' title='White Queen'/><img class='boximgs drag' id='bk' src='Pieces/blackKing.png'  title='Black King'/><img class='boximgs drag' id='wk' src='Pieces/whiteKing.png'  title='White King'/><img class='boximgs drag' id='br' src='Pieces/blackRook.png'  title='Black Rook'/><img class='boximgs drag' id='wr' src='Pieces/whiteRook.png'  title='White Rook'/><img class='boximgs drag' id='bp' src='Pieces/blackPawn.png'  title='Black Pawn'/><img class='boximgs drag' id='wp' src='Pieces/whitePawn.png'  title='White Pawn'/><img class='boximgs drag' id='bn' src='Pieces/blackKnight.png' title='Black Knight'/><img class='boximgs drag' id='wn' src='Pieces/whiteKnight.png' title='White Knight'/><img class='boximgs drag' id='bb' src='Pieces/blackBishop.png' title='Black Bishop'/><img class='boximgs drag' id='wb' src='Pieces/whiteBishop.png' title='White Bishop'/></div></div>"
	$('#confirmPass').append(newSec);
}